GET http://localhost:5275


###
GET http://localhost:5275/Home

###
GET http://localhost:5275/Home/About?param={"a":"abra","c":2}

###
GET http://localhost:5275/FingerPrintDevice

###
GET http://localhost:5275/FingerPrintDevice/openDevice

###
GET http://localhost:5275/FingerPrintDevice/getVersion

###
GET http://localhost:5275/FingerPrintDevice/deviceCount

###
GET http://localhost:5275/FingerPrintDevice/deviceNames

###
GET http://localhost:5275/FingerPrintDevice/capture

###
GET http://localhost:5275/FingerPrintDevice/convert

###
GET http://localhost:5275/FingerPrintDevice/closeDevice


###
GET http://localhost:5275/FingerPrintDevice/longRunningTask

###
GET http://localhost:5275/FingerPrintDevice/closeDevice/json