GET http://localhost:5275


###
GET http://localhost:5275/Home

###
GET http://localhost:5275/Home/About?param={"a":"abra","c":2}

###
GET http://localhost:5275/FingerPrintDevice

###
GET http://localhost:5275/FingerPrintDevice/initialize

###
GET http://localhost:5275/FingerPrintDevice/closeDevice/json